import{S as v,a as S,i}from"./assets/vendor-D2fEQMtT.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const d=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const r=o.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}">
        </a>
        <ul class="img-info">
          <li><b>Likes:</b> ${e.likes}</li>
          <li><b>Views:</b> ${e.views}</li>
          <li><b>Comments:</b> ${e.comments}</li>
          <li><b>Downloads:</b> ${e.downloads}</li>
        </ul>
      </li>
    `).join("");d.insertAdjacentHTML("beforeend",r),q.refresh()}function R(){d.innerHTML=""}function y(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}function g(){h.classList.remove("is-hidden")}function a(){h.classList.add("is-hidden")}const E="https://pixabay.com/api/",B="53339323-41a78725396da037424652e11";async function L(o,r=1){const e={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15};return(await S.get(E,{params:e})).data}const b=document.querySelector(".form"),M=document.querySelector(".load-more");let u="",n=1;const w=15;a();b.addEventListener("submit",P);M.addEventListener("click",$);async function P(o){o.preventDefault();const r=o.target.elements["search-text"].value.trim();if(!r){i.error({message:"Enter search query!",position:"topRight"});return}u=r,n=1,R(),a(),y();try{const e=await L(u,n);if(e.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),e.totalHits>w?g():i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),b.reset()}catch(e){i.error({message:"Error fetching images",position:"topRight"}),console.error(e)}finally{p()}}async function $(){n+=1,a(),y();try{const o=await L(u,n);m(o.hits),O(),n*w>=o.totalHits?(a(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):g()}catch(o){i.error({message:"Error fetching images",position:"topRight"}),console.error(o)}finally{p()}}function O(){const o=document.querySelector(".gallery-item"),{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
